#!/bin/sh
#!/bin/sh

################
#echo "Enter Continent:"
#read c
#echo "Enter City:"
#read cn
#now=$(export TZ="$c/$cn"; date)
#echo $now
#######################

	read location

	now=$(export TZ="$location"; date)

	echo $now
