#!/bin/sh

DIALOG=${DIALOG=dialog}


while true
do
	
	

	DIALOG=${DIALOG=dialog}

	$DIALOG --inputbox "Enter Continent/City:" 8 35 2>/tmp/input.$$

	now1=$(export TZ=`cat /tmp/input.$$`;date)
	na=`cat /tmp/input.$$`

	MSG="Time and date is: \\n \\n$now1"

	$DIALOG --msgbox "$MSG" 8 35 

	MSG="Do you want to continue? "

	$DIALOG --yesno "$MSG" 8 35 || end

done
